Fix ContinuesEquation
leachim6/hello-world pull request #1035
Opened 2021-05-30 23:37 UTC by MrBrain295

## Adding a language

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
The above don’t apply

2021-06-03 07:06 UTC, Richienb commented
Looks like there is also a comma

2021-06-03 11:54 UTC, MrBrain295 commented
Done @Richienb

2021-06-19 06:43 UTC, Richienb requested changes
The file appears to be incorrectly named and needs to be renamed from `ContinuesEquation` to [`ContinuousEquation`](https://esolangs.org/wiki/ContinuousEquation).

2021-06-19 06:43 UTC, Richienb commented on c/ContinuesEquation.ce
> +0 0 o'H'e'l'l'o' 'W'o'r'l'd'
Each single quote should be followed by an ascii character.

```suggestion
0 0 o'H'e'l'l'o' 'W'o'r'l'd
```

2021-08-18 12:20 UTC, merged