Add Kotlin DSL
leachim6/hello-world pull request #1096
Opened 2021-06-23 17:07 UTC by d1snin

## Adding a language

- [x ] The code displays "Hello World"
- [x ] I have updated the readme to include the new language
- [x ] I have incremented the language count in the readme

2021-06-23 17:10 UTC, MrBrain295 approved these changes
Looks good!

2021-07-01 20:17 UTC, Richienb commented
What's the difference between Kotlin DSL and "regular" Kotlin?

2021-07-01 21:36 UTC, d1snin commented
> What's the difference between Kotlin DSL and "regular" Kotlin?

In fact, this is a little different and different from the pull request code, just then I read somewhere that the build file `build.gradle` can also be in the `.gradle.kts` format, and it clearly stated about the use of a certain Kotlin DSL in this file, of course, I only later realized what it was, you can search for information about it and find more than I will say. By the way this should be renamed to something like Kotlin Script by my stupidity ¯\_(ツ)_/¯

2021-07-10 18:30 UTC, d1snin commented
merge when

2021-07-11 12:26 UTC, Richienb requested changes
The language count should be updated

2021-07-13 08:47 UTC, d1snin commented
done

2021-07-13 13:20 UTC, Richienb requested changes

2021-07-13 13:20 UTC, Richienb commented on readme.md
> +* [Kotlin Script](k/KotlinDSL.kts)
File name is not consistent with the actual file

2021-08-31 12:07 UTC, Richienb requested changes
The file name and language name in the readme need to agree on whether there should be a space between `Kotlin` and `Script`.

2021-08-31 12:56 UTC, d1snin commented
thats literally horrible. but okay np
if you want

2021-08-31 12:58 UTC, Richienb approved these changes

2021-08-31 12:59 UTC, merged

2021-08-31 15:13 UTC, smokeytube commented
@everyone 
![image](https://user-images.githubusercontent.com/67290867/131528836-8a6769ec-9adf-42ec-9179-019d3d28d63f.png)