Added Bosnian
leachim6/hello-world pull request #1171
Opened 2021-11-10 01:19 UTC by fal3n-4ngel

## Adding a language Bosnian

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language Bosnian
- [ ] I have incremented the language count in the readme.

2021-11-10 02:06 UTC, MrBrain295 commented
Why was it called Spanish?

2021-11-10 04:41 UTC, fal3n-4ngel commented
I created one for spanish and then realised Espanol exists, so changed to Bosnian

2021-11-10 12:45 UTC, MrBrain295 commented
The Bosnian language is different from Spanish.

2021-11-10 12:47 UTC, fal3n-4ngel commented
Dude , I changed the whole Script to Bosnian

2021-11-10 12:49 UTC, fal3n-4ngel commented
I first added Spanish, Then later found that it exist as Espanol, so I changed the whole script to Bosnian, So it's Now Just a new lang Bosnian

2021-11-10 20:58 UTC, MrBrain295 commented
Whoops!

2021-11-10 21:01 UTC, MrBrain295 requested changes

2021-11-10 21:01 UTC, MrBrain295 commented on #/~Bosnian
> + Zaustavite program.
I don't speak Bosnian but "program" looks to me like English.

2021-11-11 01:16 UTC, fal3n-4ngel commented on #/~Bosnian
> +Prikažite "Hello World" i novi red.
Hello World Originally Transilates to 'Zdravo svijete', but not sure that it exactly means Hello World

2021-11-11 02:09 UTC, MrBrain295 commented on #/~Bosnian
> +Prikažite "Hello World" i novi red.
What do you mean “originally translate to”?

2021-11-11 02:13 UTC, fal3n-4ngel commented
I meant as every language is different, There is no oure translation, This is the closest match

2021-11-26 03:10 UTC, Richienb approved these changes

2021-11-26 03:10 UTC, merged