Create aardio.aardio
leachim6/hello-world pull request #1173
Opened 2021-11-25 02:52 UTC by theseazhang

## Adding a language

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme

2021-11-25 15:58 UTC, MrBrain295 commented
You need to add this to the readme. Also I need a link to the languages GitHub repo or website.

2021-11-26 03:11 UTC, Richienb commented
Could you provide a link to the programming language?

2021-11-26 03:11 UTC, Richienb commented
Not sure if the name should be capitalised

2022-01-19 21:51 UTC, MrBrain295 requested changes
The readme also needs updated.

2022-01-19 21:51 UTC, MrBrain295 commented on a/aardio.aardio
> +console.log("hello world")
```suggestion
console.log("Hello World")
```

2022-01-21 22:00 UTC, closed without merging