Addes Livecode
leachim6/hello-world pull request #1189
Opened 2021-12-21 12:41 UTC by fischl-ediservice

## Adding a language

- [x ] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x ] I have incremented the language count in the readme

2021-12-21 15:16 UTC, MrBrain295 reviewed
You also need to update the readme and provide a link to the languages website or code.

2021-12-21 15:16 UTC, MrBrain295 commented on l/Livecode
> +answer "Hello World!"
It needs to print “Hello World”.

2021-12-21 22:44 UTC, MrBrain295 commented
Is it Livecode or Livescript?

2021-12-22 03:24 UTC, Richienb commented
It appears to be called **LiveCode**, which the capitalisation should reflect in this PR.

https://lessons.livecode.com/m/2592/l/21009-hello-world

2021-12-24 04:52 UTC, Richienb requested changes
The capitalisation of the filename should also be changed

2022-01-20 21:16 UTC, ThePeeps191 commented
I have added these changes in #1246

2022-01-20 21:48 UTC, closed without merging