Added !, #hell and $_$
leachim6/hello-world pull request #1203
Opened 2022-01-05 08:44 UTC by Abelkrijgtalles

## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

#### Link to programming language: 
!: https://github.com/Dylan-Middendorf/Negation, https://esolangs.org/wiki/!
#hell: https://esolangs.org/wiki/HashHell
$_$: https://github.com/Sxakalo/SUS, https://esolangs.org/wiki/$_$

2022-01-05 10:40 UTC, Richienb requested changes
> The code displays "Hello World"
Does not appear to be the case

2022-01-06 13:23 UTC, Abelkrijgtalles commented
Do you mean by $_$? Because that Is not something like
`print("Hello world")`

2022-01-07 03:27 UTC, Richienb commented
> Do you mean by $_$? Because that Is not something like `print("Hello world")`

Yes. Changing it appears to be easy though since each letter seems to be seperated by an ampersand. https://esolangs.org/wiki/$_$

2022-01-07 03:37 UTC, MrBrain295 commented on #/#hell
> +io.write("Hello, World!")
This needs to be “Hello World”.

2022-01-07 20:09 UTC, closed without merging

2022-01-07 22:00 UTC, MrBrain295 commented
@Abelkrijgtalles why did you close this?