Add Rails
leachim6/hello-world pull request #1280
Opened 2022-01-23 22:39 UTC by Tyler887

## Adding a language

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language
- [ ] I have incremented the language count in the readme
- [ ] I have no association with the language
- [ ] There are no copyright issues with this code

#### Link to programming language: 
https://rubyonrails.org

2022-01-23 22:50 UTC, MrBrain295 requested changes
It should only be `Ruby on Rails`.

2022-01-23 22:57 UTC, Tyler887 commented
> It should only be `Ruby on Rails`.

@MrBrain295 Thanks, request @Richienb to review

2022-01-23 23:27 UTC, MrBrain295 commented on readme.md
> +* [Rails](r/Rails.rb)<br /><sup>Attrib: guide https://guides.rubyonrails.org/getting_started.html under <a href="https://creativecommons.org/licenses/by-sa/4.0">Creative Commons Attribution-ShareAlik
```suggestion
* [Rails](r/Rails.rb)
```

2022-01-23 23:37 UTC, 3in0 commented
Isn't Rails more of a framework based on Ruby?
https://stackoverflow.com/questions/1237372/what-is-the-difference-between-ruby-and-ruby-on-rails/26759107

2022-01-23 23:41 UTC, MrBrain295 commented
> Isn't Rails more of a framework based on Ruby? https://stackoverflow.com/questions/1237372/what-is-the-difference-between-ruby-and-ruby-on-rails/26759107

It is but be also accept things like libraries and frameworks (that's why we have things like React).

2022-01-24 10:57 UTC, Richienb requested changes
The file is still called "Ruby on Rails"

2022-01-24 21:33 UTC, merged