Add Turtle Script
leachim6/hello-world pull request #1330
Opened 2022-03-04 09:18 UTC by gnuhead-chieb

## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language
- [x] There are no copyright issues with this code
- [x] The language has not been added prior to this pull request

#### Link to programming language: 
https://apps.kde.org/kturtle/
https://edu.kde.org/kturtle/

2022-03-04 16:33 UTC, MrBrain295 commented on r/Rapira.rap
> +output: "Hello world";
```suggestion
output: "Hello World";
```

2022-03-10 00:00 UTC, Richienb approved these changes

2022-03-10 00:03 UTC, MrBrain295 requested changes

2022-03-10 00:03 UTC, MrBrain295 commented on x/X10.x10
> +
Keep the copyright but remove the other comments.

2022-03-10 00:06 UTC, MrBrain295 reviewed
It looks as though `ThotPatrol` is an interpreted language with a `.txt`file extension so I don't see why it is appearing as a binary executable in GitHub's file viewer.

2022-03-10 00:11 UTC, MrBrain295 reviewed
What is `.X10.x10.kate-swp`?

2022-03-10 00:15 UTC, gnuhead-chieb commented
> It looks as though `ThotPatrol` is an interpreted language with a `.txt`file extension so I don't see why it is appearing as a binary executable in GitHub's file viewer.

ThotPatrol require UTF-16(Not UTF-8) for file encoding.otherwise we can not run the program.
so it cause github's bug.

> What is `.X10.x10.kate-swp`?

Ah,it mistaked.my text editor automaticlly created this file

2022-03-10 00:19 UTC, MrBrain295 approved these changes

2022-03-10 01:21 UTC, merged