added jcl
leachim6/hello-world pull request #1402
Opened 2022-10-03 13:13 UTC by jilloestreicher

## Adding a language

- [x] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme
- [x] I have no association with the language
- [x] There are no copyright issues with this code
- [x] The language has not been added prior to this pull request

#### Link to programming language:

2022-10-04 00:17 UTC, Richienb requested changes
where code

2022-10-04 03:14 UTC, jilloestreicher commented
code is the jcl.text file in the j folder

2022-10-04 03:16 UTC, Richienb requested changes
Should the extension be `.text`?

2022-10-04 03:16 UTC, Richienb requested changes
Remember to update the languages count

2022-10-04 03:22 UTC, jilloestreicher commented
oh sorry, should be .jcl

2022-10-04 12:33 UTC, jilloestreicher commented
I updated the languages count as well

2022-10-04 12:59 UTC, Richienb requested changes
Should the file name also be in all caps like the link text in the readme?

2022-10-04 13:55 UTC, jilloestreicher commented
okay I updated it to JCL.jcl

2022-10-05 06:51 UTC, Richienb requested changes
The file name still needs to be updated

2022-10-09 01:25 UTC, Richienb requested changes

2022-10-09 01:25 UTC, Richienb commented on j/JCL.jcl
> +HELLO, WORLD
Wouldn't this [print `HELLO, WORLD` instead of `HELLO WORLD`](https://www.youtube.com/watch?v=XbuKDC_n3N4&t=649s)?

2022-10-19 12:33 UTC, closed without merging