Adding Coq hello world program
leachim6/hello-world pull request #1423
Opened 2022-10-28 22:58 UTC by pierrbt

## Adding a language

- [Y] The code displays "Hello World" ([tio.run](https://tio.run) may help for testing)
- [Y] I have updated the readme to include the new language
- [Y] I have incremented the language count in the readme
- [Y] I have no association with the language
- [Y] There are no copyright issues with this code
- [Y] The language has not been added prior to this pull request

#### Link to programming language: 

https://coq.inria.fr/

2022-10-29 01:06 UTC, pierrbt commented
The program also asks the user his name but we can remove it if you prefer

2022-10-29 08:42 UTC, Richienb requested changes
Only a single Hello World example should be in the file

2022-10-29 16:34 UTC, MrBrain295 requested changes
It needs to print “Hello World” and do nothing else.

2022-10-29 17:23 UTC, pierrbt commented
Ok i'll modify it

2022-10-30 23:55 UTC, pierrbt commented
I removed all the useless things and update the langages counter

2022-10-30 23:56 UTC, pierrbt reviewed
I removed all the useless things and updated the langages counter.

2022-10-30 23:57 UTC, pierrbt reviewed
I removed all the useless things and updated the langages counter.

2022-10-31 00:08 UTC, MrBrain295 commented on c/Coq.v
> +  System.log (LString.s "Hello world!").
```suggestion
  System.log (LString.s "Hello World").
```

2022-10-31 00:09 UTC, MrBrain295 approved these changes

2022-10-31 00:09 UTC, merged

2022-10-31 00:10 UTC, MrBrain295 commented
Forgot to rename the PR 😬.