Create Octave.m
leachim6/hello-world pull request #794
Opened 2020-09-04 12:40 UTC by suryavamsi6

Hello World in Octave

2020-09-04 14:07 UTC, Richienb requested changes
Remember to update the readme.

2020-09-04 14:07 UTC, Richienb commented on o/Octave.m
> +printf("Hello World!");
```suggestion
printf("Hello World");
```

2020-09-05 01:14 UTC, Richienb commented
Is the file extension for Octave `.m` or `.octave`?

2020-09-05 07:25 UTC, suryavamsi6 commented
> Is the file extension for Octave `.m` or `.octave`?

it is '.m', the same as MATLAB

2020-10-01 00:56 UTC, merged