Added 4 new languages and updated 1 language
leachim6/hello-world pull request #803
Opened 2020-09-30 18:06 UTC by kulkarnip150

2020-10-01 00:40 UTC, Richienb requested changes
All of the files should be uppercase

2020-10-09 07:32 UTC, nithinkodadhavadee commented
@Richienb What exactly do you mean by "All files should be in uppercase"? 
And what should the file contain, few of the files @kulkarnip150 added has the translation of "Hello World" in the language and few have "Hello World" typed in the language script(seems like what a Google Translate would do).

2020-10-09 07:34 UTC, Richienb commented on README.md
> +* [~Hausa](%23/~hausa.ext)
As you can see, the linked files are lowercase.

2020-10-09 08:32 UTC, Richienb commented
@kulkarnip150 My bad. I mean the first letter needs to be capitalised.

2020-10-09 08:37 UTC, kulkarnip150 reviewed
Capitalize all file names and in readme.md file also

2020-11-17 21:59 UTC, merged