Add Darwin
leachim6/hello-world pull request #839
Opened 2020-10-14 09:01 UTC by nithinkodadhavadee

2020-10-14 10:07 UTC, Richienb commented
@nithinkodadhavadee Can you send a link to a page featuring the Darwin programming language?

2020-10-14 12:53 UTC, nithinkodadhavadee commented
https://people.inf.ethz.ch/gonnet/DarwinManual/node4.html

the documentation for the language.

2020-10-14 19:32 UTC, Richienb commented
Should it be [`printf`](https://people.inf.ethz.ch/gonnet/DarwinManual/node35.html) instead of `lprint`?

2020-10-15 05:14 UTC, nithinkodadhavadee commented
Well, there are ```[print](https://people.inf.ethz.ch/gonnet/DarwinManual/node22.html)``` and a ```[lprint](https://people.inf.ethz.ch/gonnet/DarwinManual/node22.html)``` statement too. SoI guess everything works.

2020-10-16 18:22 UTC, nithinkodadhavadee commented
hey @Richienb, is this pull request valid or should I close it? Or are there any changes to do here? I have this thing where I don't like it when a pull request is left open and nothing is going on.

2020-10-16 18:28 UTC, nithinkodadhavadee commented
and yes I have a question. In this pull request, I can see some older commits that I made which are already merged to the repository. Is this something that happens usually(a thing that I haven't noticed anywhere) so did I do something wrong?
![image](https://user-images.githubusercontent.com/50230678/96295114-020ca580-100b-11eb-83fe-7fb5c2c5b1fa.png)

2020-10-17 11:36 UTC, Richienb commented
@nithinkodadhavadee 

> Is this something that happens usually(a thing that I haven't noticed anywhere) so did I do something wrong?

2020-10-17 11:37 UTC, Richienb requested changes
Shouldn't the file have a `.drw` extension? See: https://en.wikipedia.org/wiki/Darwin_(programming_language)

2020-10-17 13:23 UTC, nithinkodadhavadee commented
> Shouldn't the file have a `.drw` extension? See: https://en.wikipedia.org/wiki/Darwin_(programming_language)

sorry I didn't notice the extension. I also changed the print function to printf(), most people refer the Wikipedia than the lecture notes, so changed it to what people might notice first.

2020-10-17 13:26 UTC, nithinkodadhavadee commented
> @nithinkodadhavadee
> 
> > Is this something that happens usually(a thing that I haven't noticed anywhere) so did I do something wrong?

I'm sorry I don't understand, you haven't typed anything.

2020-10-18 00:11 UTC, Richienb commented
@nithinkodadhavadee There was supposed to be a comment but somehow it's not there. I've updated it now.

2020-10-18 00:23 UTC, Richienb requested changes

2020-10-18 00:23 UTC, Richienb commented on d/Darwin.drw
> +printf('Hello World")
Which type of quote are we using, `'` or `"`?

2020-10-18 12:25 UTC, merged