Add Hello World! from Salesforce Lightning Web Component
leachim6/hello-world pull request #867
Opened 2020-11-19 14:14 UTC by arufian

Add Hello World! from Salesforce Lightning Web Component (LWC)

2020-11-19 19:34 UTC, Richienb requested changes

2020-11-19 19:34 UTC, Richienb commented on l/lwc.html
> +      <p>Hello World!</p>
```suggestion
      <p>Hello World</p>
```

2020-11-19 19:34 UTC, Richienb commented on l/lwc.html
> +  <lightning-card title="HelloWorld" icon-name="custom:custom14">
Do we need to set an icon or title here?

2020-11-19 19:34 UTC, Richienb commented on README.md
> +* [Lightning Web Component](l/lwc.html)
Remember to also update the languages count.

2020-11-20 07:00 UTC, arufian commented
@Richienb thanks for pointing out. Will fix it asap.

2020-11-20 09:48 UTC, merged