add BTM file
leachim6/hello-world pull request #965
Opened 2021-04-06 02:58 UTC by Guest257351

## Adding a language

- [ ] The code displays "Hello World"
- [ ] I have updated the readme to include the new language
this file is a version of batch where the script is loaded to memory before running

2021-04-06 20:35 UTC, MrBrain295 approved these changes

2021-04-07 00:59 UTC, frasca617 approved these changes

2021-04-07 04:27 UTC, Richienb commented
What is a btm file?

2021-04-07 05:21 UTC, Guest257351 commented
> What is a btm file?

Batch to memory file.

2021-04-17 14:51 UTC, Richienb requested changes
Capitalise the file name

2021-05-07 06:42 UTC, merged