Add Unreal Script
leachim6/hello-world pull request #982
Opened 2021-04-13 21:47 UTC by MrBrain295

Add Unreal Script.

## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

2021-04-13 21:49 UTC, frasca617 approved these changes

2021-04-13 21:50 UTC, MrBrain295 commented on u/Unreal Script.uc
> +  Super.PostBeginPlay(); // Run the super class function (Mutator.PostBeginPlay).
Should I remove the comments?

2021-04-13 21:52 UTC, frasca617 approved these changes

2021-04-17 00:33 UTC, Richienb requested changes

2021-04-17 00:33 UTC, Richienb commented on readme.md
> +*[Unreal Script](u/Unreal%20Script.uc)
```suggestion
* [Unreal Script](u/Unreal%20Script.uc)
```

2021-04-17 00:33 UTC, Richienb commented on u/Unreal Script.uc
> +  Super.PostBeginPlay(); // Run the super class function (Mutator.PostBeginPlay).
Yes

2021-04-17 00:42 UTC, merged