Add PeopleCode
leachim6/hello-world pull request #989
Opened 2021-04-18 13:24 UTC by MrBrain295

## Adding a language

- [x] The code displays "Hello World"
- [x] I have updated the readme to include the new language
- [x] I have incremented the language count in the readme

2021-04-18 13:26 UTC, MrBrain295 commented
Fixes part of #790

2021-04-19 23:52 UTC, MrBrain295 commented
@Richienb is there anything i need to fix

2021-04-21 00:14 UTC, Richienb requested changes

2021-04-21 00:14 UTC, Richienb commented on p/PeopleCode
> +MessageBox(0,"",0,0,"Hello World");
```suggestion
MessageBox(0, "", 0, 0, "Hello World");
```

2021-04-21 01:01 UTC, merged